/*
 * UTM DSS/USS API
 *
 * Interface to Discovery and Synchronization Service (DSS) and UAS Service Suppliers (USS) used by participating clients to discover and interoperate.  Unless otherwise specified, fields specified in a message but not declared in the API shall be ignored.
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Response to a request to create, update, or delete a ConstraintReference. in the DSS.
    /// </summary>
    [DataContract]
    public partial class ChangeConstraintReferenceResponse : IEquatable<ChangeConstraintReferenceResponse>
    { 
        /// <summary>
        /// DSS subscribers that this client now has the obligation to notify of the Constraint changes just made.  This client must call POST for each provided URL according to the &#x60;/uss/constraints/{id}&#x60; path API.
        /// </summary>
        /// <value>DSS subscribers that this client now has the obligation to notify of the Constraint changes just made.  This client must call POST for each provided URL according to the &#x60;/uss/constraints/{id}&#x60; path API.</value>
        [Required]
        [DataMember(Name="subscribers")]
        public List<SubscriberToNotify> Subscribers { get; set; }

        /// <summary>
        /// Resulting ConstraintReference stored in DSS.  Omitted if and only if ConstraintReference was deleted.
        /// </summary>
        /// <value>Resulting ConstraintReference stored in DSS.  Omitted if and only if ConstraintReference was deleted.</value>
        [DataMember(Name="constraint_reference")]
        public AnyOfChangeConstraintReferenceResponseConstraintReference ConstraintReference { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ChangeConstraintReferenceResponse {\n");
            sb.Append("  Subscribers: ").Append(Subscribers).Append("\n");
            sb.Append("  ConstraintReference: ").Append(ConstraintReference).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ChangeConstraintReferenceResponse)obj);
        }

        /// <summary>
        /// Returns true if ChangeConstraintReferenceResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of ChangeConstraintReferenceResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ChangeConstraintReferenceResponse other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Subscribers == other.Subscribers ||
                    Subscribers != null &&
                    Subscribers.SequenceEqual(other.Subscribers)
                ) && 
                (
                    ConstraintReference == other.ConstraintReference ||
                    ConstraintReference != null &&
                    ConstraintReference.SequenceEqual(other.ConstraintReference)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Subscribers != null)
                    hashCode = hashCode * 59 + Subscribers.GetHashCode();
                    if (ConstraintReference != null)
                    hashCode = hashCode * 59 + ConstraintReference.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ChangeConstraintReferenceResponse left, ChangeConstraintReferenceResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ChangeConstraintReferenceResponse left, ChangeConstraintReferenceResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
