/*
 * UTM DSS/USS API
 *
 * Interface to Discovery and Synchronization Service (DSS) and UAS Service Suppliers (USS) used by participating clients to discover and interoperate.  Unless otherwise specified, fields specified in a message but not declared in the API shall be ignored.
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Details of a UTM Constraint. Note that this data is not stored in the DSS; only with the clients.
    /// </summary>
    [DataContract]
    public partial class ConstraintDetails : IEquatable<ConstraintDetails>
    { 
        /// <summary>
        /// Volumes that wholly contain the Constraint while being as small as practical.
        /// </summary>
        /// <value>Volumes that wholly contain the Constraint while being as small as practical.</value>
        [Required]
        [DataMember(Name="volumes")]
        public List<Volume4D> Volumes { get; set; }

        /// <summary>
        /// List of Operations exempt from this Constraint, if applicable.
        /// </summary>
        /// <value>List of Operations exempt from this Constraint, if applicable.</value>
        [DataMember(Name="exempt_operations")]
        public List<EntityUUID> ExemptOperations { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ConstraintDetails {\n");
            sb.Append("  Volumes: ").Append(Volumes).Append("\n");
            sb.Append("  ExemptOperations: ").Append(ExemptOperations).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ConstraintDetails)obj);
        }

        /// <summary>
        /// Returns true if ConstraintDetails instances are equal
        /// </summary>
        /// <param name="other">Instance of ConstraintDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ConstraintDetails other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Volumes == other.Volumes ||
                    Volumes != null &&
                    Volumes.SequenceEqual(other.Volumes)
                ) && 
                (
                    ExemptOperations == other.ExemptOperations ||
                    ExemptOperations != null &&
                    ExemptOperations.SequenceEqual(other.ExemptOperations)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Volumes != null)
                    hashCode = hashCode * 59 + Volumes.GetHashCode();
                    if (ExemptOperations != null)
                    hashCode = hashCode * 59 + ExemptOperations.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ConstraintDetails left, ConstraintDetails right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ConstraintDetails left, ConstraintDetails right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
