/*
 * UTM DSS/USS API
 *
 * Interface to Discovery and Synchronization Service (DSS) and UAS Service Suppliers (USS) used by participating clients to discover and interoperate.  Unless otherwise specified, fields specified in a message but not declared in the API shall be ignored.
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Endpoints that should be called when an applicable event occurs.  At least one field must be specified.
    /// </summary>
    [DataContract]
    public partial class SubscriptionCallbacks : IEquatable<SubscriptionCallbacks>
    { 
        /// <summary>
        /// If specified, other clients will be instructed by the DSS to call this endpoint when an Operation relevant to this Subscription is created, modified, or deleted.  Must implement POST according to the &#x60;/uss/operations/{id}&#x60; path API.
        /// </summary>
        /// <value>If specified, other clients will be instructed by the DSS to call this endpoint when an Operation relevant to this Subscription is created, modified, or deleted.  Must implement POST according to the &#x60;/uss/operations/{id}&#x60; path API.</value>
        [DataMember(Name="operation_url")]
        public AnyOfSubscriptionCallbacksOperationUrl OperationUrl { get; set; }

        /// <summary>
        /// If specified, other clients will be instructed by the DSS to call this endpoint when a Constraint relevant to this Subscription is created, modified, or deleted.  Must implement POST according to the &#x60;/uss/constraints/{id}&#x60; path API.
        /// </summary>
        /// <value>If specified, other clients will be instructed by the DSS to call this endpoint when a Constraint relevant to this Subscription is created, modified, or deleted.  Must implement POST according to the &#x60;/uss/constraints/{id}&#x60; path API.</value>
        [DataMember(Name="constraint_url")]
        public AnyOfSubscriptionCallbacksConstraintUrl ConstraintUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SubscriptionCallbacks {\n");
            sb.Append("  OperationUrl: ").Append(OperationUrl).Append("\n");
            sb.Append("  ConstraintUrl: ").Append(ConstraintUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SubscriptionCallbacks)obj);
        }

        /// <summary>
        /// Returns true if SubscriptionCallbacks instances are equal
        /// </summary>
        /// <param name="other">Instance of SubscriptionCallbacks to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SubscriptionCallbacks other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    OperationUrl == other.OperationUrl ||
                    OperationUrl != null &&
                    OperationUrl.SequenceEqual(other.OperationUrl)
                ) && 
                (
                    ConstraintUrl == other.ConstraintUrl ||
                    ConstraintUrl != null &&
                    ConstraintUrl.SequenceEqual(other.ConstraintUrl)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (OperationUrl != null)
                    hashCode = hashCode * 59 + OperationUrl.GetHashCode();
                    if (ConstraintUrl != null)
                    hashCode = hashCode * 59 + ConstraintUrl.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(SubscriptionCallbacks left, SubscriptionCallbacks right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SubscriptionCallbacks left, SubscriptionCallbacks right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
